project/accounts/urls.py
from accounts import views
from django.conf.urls import url
from django.contrib import admin
from django.urls import reverse_lazy

from .views import *

admin.autodiscover()

app_name = 'accounts'

urlpatterns = [
    url(r'^login/$', login_user, name='login'),
    url(r'^signup/$', register, name='signup'),
    url(r'^profile/$', profile, name='profile'),
    url(r'^home_page/$', home_page, name='home_page'),
    ]

project/api/urls.py
from django.conf.urls import url 
from api import views 
 
urlpatterns = [ 
    url('product/', views.ProductList.as_view()),
    url('product/<int:pk>/', views.ProductDetail.as_view()),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include 
 


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('api.urls')),
    url(r'accounts/', include('accounts.urls')),

]

project/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

STATUS = ((0, "Pending"), (1, "Approve"), (2, "Rejected"), (3, "Block"))
from django.contrib.auth.base_user import BaseUserManager

# Create your models here.
class Products(models.Model):
    title = models.CharField(max_length=70, blank=False, default='')
    description = models.CharField(max_length=200,blank=False, default='')
    published = models.BooleanField(default=False)

class class_name(models.Model):
    name = models.CharField(max_length=200,null=True,blank=True)
    class Meta:
    	managed = True
    	db_table = 'tbl_class'
    def __str__(self):
    	if self.name:
    		return "{} ({})".format(self.name, self.id)
   
class CustomUserManager(BaseUserManager):
    
    def create_user(self, email, password, **extra_fields):
        
        
        if not email:
            raise ValueError(_('The Email must be set'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_('Superuser must have is_staff=True.'))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_('Superuser must have is_superuser=True.'))
        return self.create_user(email, password, **extra_fields)



class User(AbstractUser):
	class_name = models.ForeignKey(class_name, on_delete=models.CASCADE, related_name="addresses",null=True,blank=True)
	first_name = models.CharField(max_length=50, null=True, blank=True)
	# username = None
	# USERNAME_FIELD = 'email'
	# REQUIRED_FIELDS = []
	username = models.CharField(max_length=50, null=True, blank=True)
	last_name = models.CharField(max_length=50, null=True, blank=True)
	email = models.CharField(max_length=100, null=True, blank=True,unique=True)
	email_verifY = models.BooleanField(default=False)
	date_of_birth = models.CharField(max_length=100, null=True, blank=True)
	image = models.ImageField(upload_to='profile_pic/', blank=True, null=True)
	status = models.PositiveIntegerField(default=0, choices=STATUS)
	# objects = CustomUserManager()

	class Meta:
		managed = True
		db_table = 'tbl_user'
	def __str__(self):
		if self.email:
			return "{} ({})".format(self.email, self.id)

project/accounts/views.py
from django.shortcuts import render
from django.contrib import auth
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login
from django.contrib.auth import login
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password
from django.http import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, View
from django.views.generic.edit import CreateView
from accounts.models import *
from django.contrib.auth import get_user_model
from django.contrib.auth import login, authenticate
# Create your views here.

User = get_user_model()


def home_page(request):
    return render(request, 'accounts/index.html', {})
@csrf_exempt
def login_user(request, template_name=None, extra_context=None):
    if request.method == 'POST':
        print(request.POST.get('username'),"sssssss")
        
        email = request.POST.get('email')
        password = request.POST.get('password')
        user=User.objects.filter(email=email)
        
        user = authenticate(username=email, password=password)
        
        print(user,"ss")

        if user:
            if user.is_superuser:
                
                login(request, user)
                return redirect('admin:index')
            if user.status == 0:
                login(request, user)
                messages.error(request, 'login successfull')
                return redirect('accounts:home_page')
            

            else:
                messages.error(request, 'Email or password not correct')
                return redirect('accounts:login')
          
            
        else:
            messages.error(request, 'Email or password not correct')
            return redirect('accounts:login')
    else:
        

        return render(request, 'accounts/login.html', {})


def register(request):
    if request.method == 'POST':
            
        
       
            # if not request.POST.get('email', None) :
            #     messages.error(request, 'Registration failed! Please enter details.')
            #     return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

            # if User.objects.filter(email=request.POST.get('email', None)):
            #     messages.error(request, 'User already exist with this email id.')
            #     return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

       

            user = User.objects.create(
                email=request.POST.get('email'),
                first_name=request.POST.get('first_name'),
                last_name=request.POST.get('last_name'),
                password=request.POST.get('password'),
                date_of_birth=request.POST.get('date_of_birth'),
                class_name=request.POST.get('class_name')
            )
            

            user.set_password(user.password)
            user.save()
            messages.info(request, 'Signed Up Successfully')
            return redirect('accounts:login')
    else:
        class_names=class_name.objects.all()
        print(class_names)

        
   
        return render(request, 'accounts/signup.html', {"class_names":class_names})

@login_required(login_url='/user/login')
def profile(request):
    if request.method=="POST":

        user=User.objects.get(id=request.user.id)  
        if user.is_superuser:
            return redirect('admin:index')
        try:  
                  
            
                try:
                    user=User.objects.get(id=request.user.id)                       
                    if request.POST.get('first_name'):
                        user.first_name=request.POST.get('first_name')
                    if request.POST.get('last_name'):
                        user.last_name=request.POST.get('last_name')
                    if request.POST.get('email'):
                        user.email  =request.POST.get('email')            
                    if request.POST.get('date_of_birth'):
                        user.date_of_birth=date_of_birth 
                    if request.POST.get('class_name'):
                        user.class_name=class_name 
                    user.save()              
                except:               
                    user=User.objects.create(first_name=request.POST.get('first_name'),
                                        last_name=request.POST.get('last_name'),                                    
                                        email=request.POST.get('email'),
                                        date_of_birth=request.POST.get('date_of_birth'),
                                        class_name=request.POST.get('class_name'),
                                        
                                        )                                                      
                
                    
               
                messages.success(request, 'Profile Edited successfully')
                return redirect(request.META.get("HTTP_REFERER"))
            
        except Exception as e:
            print(e)
            messages.warning(request, "Unable To Save Profile Update.")
            return redirect(request.META.get("HTTP_REFERER")) 


    else:
            class_names=class_name.objects.all()
            
       
            user=User.objects.all()
            
            return render(request, "accounts/profile.html",
                            {"class_names":class_names})



def logout(request):
    if request.user.is_superuser:
        auth.logout(request)
        return redirect('accounts:signup') 
        
    else:

        try:
            auth.logout(request)
            return redirect('accounts:login')
        except Exception:
            return render(request, settings.EXCEPTION_TEMPLATE)

project/templates/accounts/index.html
<a href="{% url 'accounts:profile' %}">profile</a>

project/templates/accounts/login.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width,initial-scale=1,user-scalable=0,minimal-ui"
          name="viewport">
    <title>Test Project</title>
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <!-- App Icons -->
    <link href="{% static 'assets/images/favicn.ico' %}" rel="shortcut icon">
    <!-- Basic Css files -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}"
          rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/metismenu.min.css' %}"
          rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet"
          type="text/css">
</head>
<body class="fixed-left">
<!-- Loader -->
<div id="preloader">
    <div id="status">
        <div class="spinner"></div>
    </div>
</div>
<!-- Begin page -->
<div class="accountbg"></div>
<div class="wrapper-page">

    <div class="card">
        <div class="card-body">
            <a class="logo my-2 d-block text-center" href="/"><img
                    alt="logo" class="logo-large"
                    src="/static/assets/images_1/e-kirana-logo.png" width=200px></a>
            <div class="pb-2">
                <div class="text-center">
                    <h3>Welcome Back!</h3>

                    <p class="text-muted mb-0">Sign in to continue.</p>
                </div>
            </div>
            <div class="p-3">
                {% for message in messages %}
                <div class="alert alert-success">
                    <a class="close" data-dismiss="alert" href="#">×</a> {{ message }}
                </div>
                {% endfor %}
                <form action="{% url 'accounts:login'%}" class="sign-in outer-top-xs"
                      method="POST">
                    <div class="form-group">
                        {% csrf_token %} <label class="info-title" for="username">Email
                        Address:</label> <input class="form-control unicase-form-control" name="email" type="text" placeholder="{% trans 'Enter Email' %}" >
                        <p class="error"></p>
                    </div>
                    <div class="form-group">
                        <label class="info-title" for="password">Password:</label> <input
                            class="form-control unicase-form-control"
                            type="password" name="password" placeholder="{% trans 'Enter Password' %}" >
                        <p class="error"></p>
                    </div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="custom-checkbox">
                                <div class="form-group">
                                    <input id="javascript" type="checkbox"> <label
                                        for="javascript">{% trans "Remember me" %}</label>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6 text-right">
                            <a class="text-muted" href=""><i
                                    class="mdi mdi-lock"></i> Forgot password?</a>


                        </div>
                    </div>
                    <div class="form-group m-t-30 mb-0 row">
                        <div class="col-12 text-center">
                            <button class="btn btn-success btn-rounded w-md waves-effect waves-light btn-block btn-lg"
                                    type="submit">
                                Log
                                In
                            </button>
                        </div>
                    </div>


                </form>
            </div>
            <div class="mt-2 text-center">
                <p>
                    Don't have an account ? <a class="font-600"
                                               href="{% url 'accounts:signup' %}">Sign up Now</a>
                </p>

            </div>
        </div>
    </div>

</div>

</p>

</div>
</div>
</div>

</div>
<!-- end wrapper-page -->
<!-- jQuery  -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/js/modernizr.min.js' %}"></script>
<script src="{% static 'assets/js/metisMenu.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
<script src="{% static 'assets/js/waves.js' %}"></script>
<!-- App js -->
<script src="{% static 'assets/js/app.js' %}"></script>
</body>
</html>

project/templates/accounts/profile.html
{% block content %}


<div class="content-page">
    <!-- Start content -->
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row align-items-center">
                            <div class="col-md-8">
                                <h4 class="page-title mb-0">Profile Page</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    {% for message in messages %}
                    <div class="alert alert-success">
                        <a class="close" data-dismiss="alert" href="#">×</a> {{ message }}
                    </div>
                    {% endfor %}
                    <!-- BEGIN PROFILE SIDEBAR -->
                    <div class="profile-sidebar py-3">
                        <div class="card card-topline-aqua">
                            <div class="card-body no-padding height-9">
                                <div class="row">
                                    <div class="profile-userpic">
                                        <p class="mb-20">PICTURE</p>
                                        {% if request.user.upload_image and request.user.upload_image != "" %}
                                        <img alt="user" src="/media/{{ request.user.upload_image }}" /> {% else %}
                                        <img alt="user" class="img-circle" src="/static/img/11.jpeg" /> {% endif %}
                                    </div>
                                </div>
                                <form action="{% url 'accounts:profile' %}" class="outer-top-xs" enctype="multipart/form-data" method="post">
                                    {% csrf_token %}
                                    <div class="form-group">
                                        <div class="upload-btn-wrapper">
                                            <label>Edit Picture</label>
                                            <input accept=".png, .jpg, .jpeg" class="form-control unicase-form-control text-input" id="imageprofile" name="upload_image" required="required" type="file" value="{{ request.user.upload_image }}">

                                        </div>
                                    </div>
                                    <div class="butn d-flex justify-content-end">
                                        <button class="btn btn-success btn-rounded w-md waves-effect waves-light btn-block btn-lg w-unset" type="submit">
                                            Update
                                        </button>
                                    </div>
                                </form>

                            </div>
                        </div>
                    </div>
                    <!-- END BEGIN PROFILE SIDEBAR -->
                    <!-- BEGIN PROFILE CONTENT -->
                    <div class="profile-content py-3">
                        <div class="card">
                            <div class="card-topline-aqua">
                                <header></header>
                            </div>
                            
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div class="tab-pane fontawesome-demo active show" id="tab1">
                                        <div id="biography">
                                            <h3 class="profile-heading text-center py-4">My Profile</h3>
                                        </div>
                                        <div class="main-form">
                                            <form action="{% url 'accounts:profile' %}" class="outer-top-xs" enctype="multipart/form-data" id="profile_form" method="post" name="myForm">
                                                {% csrf_token %}
                                                <div class="form-group">
                                                    <label>First Name</label>
                                                    <input {% if not request.user.first_name %} placeholder="First Name" {% else %} value="{{ request.user.first_name }}" {% endif %} class="form-control" type="text" name="first_name">
                                                </div>
                                                <div class="form-group">
                                                    <label>Last Name </label>
                                                    <input {% if not request.user.last_name %} placeholder="Last Name" {% else %} value="{{ request.user.last_name }}" {% endif %} class="form-control" type="text" name="last_name">
                                                </div>
                                                <div class="form-group">
                                                    <label>Email Address</label>
                                                    <input {% if not request.user.email %} placeholder="Email" {% else %} value="{{ request.user.email }}" {% endif %} class="form-control" type="text" name="email">
                                                </div>
                                                <div class="form-group">
                                                    <label>date_of_birth</label>

                                                    <input {% if not request.user.date_of_birth %} placeholder="Date birth"
                                                           {% else %} value="{{ request.user.date_of_birth }}" {% endif %} class="form-control" type="date" name="contact_no">

                                                </div>
                                                  <div class="col-sm col-sm mg-t-10 mg-sm-t-0">
                            <select class="custom-select main_category" aria-placeholder="Real Estate"
                                name="real_estate_id" required>
                                

                                {% for name in class_names %}
                                <option value="{{ name.id }}" required>{{name}}</option>
                                {% endfor %}
                            </select>
                            <p class="error text-danger" id="real_estate_id_error"></p>
                            <p class="error text-danger"></p>

                        </div>
                                               
                                                <div class="d-md-flex justify-content-end">
                                                    <button class="btn btn-success btn-rounded w-md waves-effect waves-light btn-block btn-lg w-unset" type="submit">Save
                                                    </button>
                                                </div>

                                            </form>
                                        </div>
                                        <hr>
                                    </div>
                                    
                                   
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- END PROFILE CONTENT -->
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project/templates/accounts/signup.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta content="width=device-width,initial-scale=1,user-scalable=0,minimal-ui"
          name="viewport">
    <title>Test Project</title>

    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <!-- App Icons -->
    <link href="{% static 'assets/images/favicn.ico' %}" rel="shortcut icon">
    <!-- Basic Css files -->
    <link href="{% static 'assets/css/bootstrap.min.css' %}"
          rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/metismenu.min.css' %}"
          rel="stylesheet" type="text/css">
    <link href="{% static 'assets/css/icons.css' %}" rel="stylesheet"
          type="text/css">
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet"
          type="text/css">
</head>
<body class="fixed-left">
<!-- Loader -->
<div id="preloader">
    <div id="status">
        <div class="spinner"></div>
    </div>
</div>
<!-- Begin page -->

<div class="accountbg"></div>

<div class="wrapper-page" style="max-width: 520px;">

    <div class="card">
        <div class="card-body">
            <a class="logo my-2 d-block text-center" href="/"><img
                    alt="logo" class="logo-large"
                    src="/static/assets/images_1/e-kirana-logo.png" width=200px></a>
            <div class="pb-2">
                <div class="text-center">
                    <h4 class="font-18">Sign up</h4>
                </div>
            </div>
            
          
            <div class="tab-content">
               

                <div class="tab-pane" id="tab2">
                    <form action="{% url 'accounts:signup' %}" class="registration merchant"
                          method="POST">
                        {% csrf_token %} <input name="role_id" type="hidden" value="2">
                        <div class="p-3">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="First name">First name</label> <input class="form-control"
                                                                                          name="first_name"
                                                                                          placeholder="Enter first name" type="text"
                                                                                          value="">
                                        <p class="error"></p>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="First name">Last name</label> <input class="form-control"
                                                                                         name="last_name"
                                                                                         placeholder="Enter last name"
                                                                                         type="text">
                                        <p class="error"></p>
                                    </div>
                                </div>
                            </div>


                            <div class="form-group">
                                <label for="email">Email Address</label> <input class="form-control"
                                                                                name="email" placeholder="Enter Email address"
                                                                                type="email">
                                <p class="error"></p>
                            </div>

                            <div class="form-group">
                                <label for="userpassword">Password</label> <input
                                    class="form-control" minlength="8" name="password"
                                    placeholder="Enter password" type="password">
                                <p class="error"></p>
                            </div>

                            <div class="form-group">
                                <label for="phone number">Date of birth</label> <input
                                    class="form-control" maxlength="10" minlength="10"
                                    type="date" name="date_of_birth" placeholder="Enter date of birth" type="text">
                                <p class="error"></p>
                            </div>
                            
                            <p><b>Enter Class </b></p>
                            <div class="row row-xs  ">
                        <div class="col-sm col-sm mg-t-10 mg-sm-t-0">
                            <select class="custom-select main_category" aria-placeholder="Real Estate"
                                name="real_estate_id" required>
                                <option value="" name="real_estate_id">Select class</option>
                                {% for name in class_names %}
                                <option value="{{ name.id }}" required>{{name}}</option>
                                {% endfor %}
                            </select>
                            <p class="error text-danger" id="real_estate_id_error"></p>
                            <p class="error text-danger"></p>

                        </div>

                    </div>



                        <div>
                           
                            <div class="subscription-btn login-btn">
                                <button
                                        class="btn btn-success btn-rounded w-md waves-effect waves-light btn-block btn-lg"
                                        type="submit" value="Sign Up">Sign up
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
                



            </div>
            <div class="mt-2 text-center">
                <p>
                    Already have an account? <a class="font-600"
                                                href="{% url 'accounts:login' %}">Login Now</a>
                </p>
            </div>
        </div>
    </div>

</div>
<!-- end wrapper-page -->
<!-- jQuery  -->
<script src="{% static 'assets/js/jquery.min.js' %}"></script>
<script src="{% static 'assets/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'assets/js/modernizr.min.js' %}"></script>
<script src="{% static 'assets/js/metisMenu.min.js' %}"></script>
<script src="{% static 'assets/js/jquery.slimscroll.js' %}"></script>
<script src="{% static 'assets/js/waves.js' %}"></script>
<!-- App js -->

<script src="{% static 'assets/js/app.js' %}"></script>
<!-- Main server js -->
<script src="{% static 'assets/js/e-kirana.js' %}"></script>
</body>
</html>